// Historical base rates — vendored from the main repo (lib/baseRates.ts).
// baseRate is 0–100 (percent).

export const BASE_RATES = [
  {
    id: 'incumbent_reelected',
    label: 'Incumbent president reelected',
    baseRate: 68,
    description: 'Sitting presidents seeking a second term win re-election',
    sampleSize: 22,
    timeRange: '1900–2024',
    source: 'U.S. presidential election records',
  },
  {
    id: 'fed_hold_unemp_below_4',
    label: 'Fed holds rates (unemployment < 4%)',
    baseRate: 74,
    description: 'Fed holds rates at next meeting when unemployment is below 4%',
    sampleSize: 18,
    timeRange: '2000–2026',
    source: 'Federal Reserve FOMC meeting records',
  },
  {
    id: 'fed_cut_cpi_above_3',
    label: 'Fed cuts rates when CPI > 3%',
    baseRate: 12,
    description: 'Fed cuts rates at next meeting when CPI inflation is above 3%',
    sampleSize: 14,
    timeRange: '2000–2026',
    source: 'Federal Reserve FOMC meeting records',
  },
  {
    id: 'recession_called_12mo',
    label: 'Recession declared within 12 months',
    baseRate: 28,
    description: 'NBER formally declares recession within a 12-month forward window',
    sampleSize: 15,
    timeRange: '1950–2026',
    source: 'NBER business cycle dating',
  },
  {
    id: 'sp500_positive_year',
    label: 'S&P 500 positive calendar year return',
    baseRate: 72,
    description: 'S&P 500 closes the year above its January 1 level',
    sampleSize: 74,
    timeRange: '1950–2024',
    source: 'S&P 500 annual return data',
  },
  {
    id: 'bitcoin_above_100k_eoy',
    label: 'Bitcoin > $100k by year-end',
    baseRate: 33,
    description: 'Bitcoin price exceeds $100,000 by December 31',
    sampleSize: 5,
    timeRange: '2020–2026',
    source: 'CoinGecko historical pricing',
  },
  {
    id: 'gdp_growth_above_2',
    label: 'Real GDP growth > 2% (annualized)',
    baseRate: 62,
    description: 'U.S. real GDP growth rate exceeds 2% annualized in a given quarter',
    sampleSize: 28,
    timeRange: '2000–2026',
    source: 'Bureau of Economic Analysis',
  },
  {
    id: 'cpi_above_3',
    label: 'YoY CPI inflation > 3%',
    baseRate: 38,
    description: 'U.S. Consumer Price Index year-over-year change exceeds 3%',
    sampleSize: 26,
    timeRange: '2000–2026',
    source: 'Bureau of Labor Statistics',
  },
  {
    id: 'senate_incumbent_wins_primary',
    label: 'Senate incumbent wins primary',
    baseRate: 91,
    description: 'Sitting U.S. senator wins their party primary',
    sampleSize: 44,
    timeRange: '2000–2024',
    source: 'Congressional election records',
  },
  {
    id: 'vix_below_20_eoy',
    label: 'VIX closes below 20 on year-end',
    baseRate: 58,
    description: 'CBOE VIX closes below 20 on the last trading day of the year',
    sampleSize: 34,
    timeRange: '1990–2024',
    source: 'CBOE VIX historical data',
  },
  {
    id: 'interest_rate_cut_next_meeting',
    label: 'Fed cuts rates at next meeting',
    baseRate: 31,
    description: 'Federal Reserve cuts the federal funds rate at the next scheduled FOMC meeting',
    sampleSize: 42,
    timeRange: '2000–2026',
    source: 'Federal Reserve FOMC meeting records',
  },
  {
    id: 'major_sports_upset',
    label: 'Heavy underdog wins championship',
    baseRate: 22,
    description: 'Team priced below 20¢ wins a major championship (NFL/NBA/MLB/NHL)',
    sampleSize: 30,
    timeRange: '2000–2026',
    source: 'Sports reference historical odds',
  },
]

export function getBaseRateById(id) {
  return BASE_RATES.find((r) => r.id === id)
}
